repos:
  - repo: local
    hooks:
      - id: generate-sample-env
        name: Generate .env.sample file
        entry: python scripts/generate_sample_env.py
        language: system
      
      - id: pytest-check
        stages: [commit]
        types: [python]
        name: Running the PyTest
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
      
      - id: add-all-files-generated
        stages: [commit]
        name: Adding all Generated files to the commit stage
        entry: git add .
        language: system
        always_run: true