name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheels
          pip install -r requirements.txt

      - name: Runnig tests
        run: pytest  # Replace 'pytest' with the command to run your tests
